### PR TITLE
add api_id

### PR DESCRIPTION
**Pull request by 1intan99**

### CODE REVIEW

**Comment by Algoinde** [comment]
There are new changes to the API. Would you like to add the new stuff?

**Comment by Iqrar99** [comment]
May I work on this @Algoinde? It seems there is no new progress on their side so I offer myself to help and finish it within some days.

I'll make a new PR soon if you agree. I already made an issue here #59

**Comment by Algoinde** [comment]
Ye, of course. There's also https://crowdin.com/translate/enka-network/ if you want to.

**Comment by Iqrar99** [comment]
Got it, I'm working on it now

**Pull request closed without merging**
